// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7iyh-B46IpfstjlSWOe2P1fdKeaAFhRc',
    appId: '1:311375040970:web:1ae5479546ebeb6b99ff33',
    messagingSenderId: '311375040970',
    projectId: 'ftwitter-24618',
    authDomain: 'ftwitter-24618.firebaseapp.com',
    storageBucket: 'ftwitter-24618.firebasestorage.app',
    measurementId: 'G-3C93YSRQQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCKWFX4i99CgsfBTPSm4nr6WaTUbMm7Wk',
    appId: '1:311375040970:android:caa9af6bb50caae399ff33',
    messagingSenderId: '311375040970',
    projectId: 'ftwitter-24618',
    storageBucket: 'ftwitter-24618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMmYZwvOO2CL_yAmi-KaBfOSm7TLlL6ow',
    appId: '1:311375040970:ios:4f559033fdbb263b99ff33',
    messagingSenderId: '311375040970',
    projectId: 'ftwitter-24618',
    storageBucket: 'ftwitter-24618.firebasestorage.app',
    androidClientId: '311375040970-2optuk33kptuj4lilj2dk5cp9s6edecs.apps.googleusercontent.com',
    iosClientId: '311375040970-6qee6mg7j34o2aidus00gesfbipm7ven.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracingTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMmYZwvOO2CL_yAmi-KaBfOSm7TLlL6ow',
    appId: '1:311375040970:ios:4f559033fdbb263b99ff33',
    messagingSenderId: '311375040970',
    projectId: 'ftwitter-24618',
    storageBucket: 'ftwitter-24618.firebasestorage.app',
    androidClientId: '311375040970-2optuk33kptuj4lilj2dk5cp9s6edecs.apps.googleusercontent.com',
    iosClientId: '311375040970-6qee6mg7j34o2aidus00gesfbipm7ven.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracingTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7iyh-B46IpfstjlSWOe2P1fdKeaAFhRc',
    appId: '1:311375040970:web:9692a1a04188d3de99ff33',
    messagingSenderId: '311375040970',
    projectId: 'ftwitter-24618',
    authDomain: 'ftwitter-24618.firebaseapp.com',
    storageBucket: 'ftwitter-24618.firebasestorage.app',
    measurementId: 'G-WHMC0YY4BK',
  );

}